# Copyright 2021 iLogtail Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

FROM ubuntu:25.10 AS build
ARG VERSION=0.0.1
ARG TARGETPLATFORM
WORKDIR /usr/local
# Copy the specific architecture package
COPY dist/loongcollector-${VERSION}.linux-${TARGETPLATFORM##*/}.tar.gz .
RUN tar -xzf loongcollector-${VERSION}.linux-${TARGETPLATFORM##*/}.tar.gz

FROM ubuntu:25.10 AS release

ENV container=docker

ARG HOST_OS=Linux
ARG VERSION=0.0.1
ARG TARGETPLATFORM

COPY --from=build /usr/local/loongcollector-${VERSION} /usr/local/loongcollector
RUN chown -R $(whoami) /usr/local/loongcollector/ && \
    chmod 755 /usr/local/loongcollector/loongcollector && \
    mkdir -p /usr/local/loongcollector/data/checkpoint

# Install runtime dependencies (Kerberos/SASL libs for Kafka)
RUN if [ "$HOST_OS" = "Linux" ]; then \
        apt-get update && apt-get install -y \
            libsasl2-2 \
            libsasl2-modules \
            libsasl2-modules-gssapi-mit \
            libkrb5-3 \
            libk5crypto3 \
            libgssapi-krb5-2 && \
        apt-get clean && rm -rf /var/lib/apt/lists/*; \
    fi

# Provide CentOS-compiled SASL libraries for librdkafka (expects libsasl2.so.3)
COPY --from=sls-opensource-registry.cn-shanghai.cr.aliyuncs.com/loongcollector-community-edition/loongcollector-build-linux:2.1.14 /usr/lib64/libsasl2.so.3 /usr/lib/x86_64-linux-gnu/
COPY --from=sls-opensource-registry.cn-shanghai.cr.aliyuncs.com/loongcollector-community-edition/loongcollector-build-linux:2.1.14 /usr/lib64/libsasl2.so.3.0.0 /usr/lib/x86_64-linux-gnu/
COPY --from=sls-opensource-registry.cn-shanghai.cr.aliyuncs.com/loongcollector-community-edition/loongcollector-build-linux:2.1.14 /usr/lib64/sasl2 /usr/lib/x86_64-linux-gnu/sasl2

WORKDIR /usr/local/loongcollector
RUN mkdir -p /usr/local/loongcollector/conf/instance_config/local
RUN mkdir -p /usr/local/loongcollector/log
RUN mkdir -p /usr/local/loongcollector/data
RUN mkdir -p /usr/local/loongcollector/run

COPY example_config/start_with_docker/loongcollector_config.json /usr/local/loongcollector/conf/instance_config/local/loongcollector_config.json
COPY scripts/loongcollector_control.sh /usr/local/loongcollector/

ENV HTTP_PROBE_PORT=7953 \
    ALIYUN_LOGTAIL_USER_DEFINED_ID=default \
    docker_file_cache_path=checkpoint/docker_path_config.json \
    LOONGCOLLECTOR_VERSION=$VERSION \
    HOST_OS=$HOST_OS

CMD ["/usr/local/loongcollector/loongcollector_control.sh", "start_and_block"] 